name: Build M30s A11 OneUI KernelSU-Next permissive

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            libncurses5-dev \
            libtinfo5 \
            git \
            zip \
            cpio \
            python3 \
            python-is-python3 \
            tar \
            wget \
            curl

      - name: Build Kernel
        run: |
          chmod +x build.sh ksu.sh
          chmod -R +x tools/make/bin/
          ./build.sh -d m30s -a 11 -v oneui -k -p -c

      - name: Upload Kernel ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Mint-Kernel-M30s-A11-OneUI-KSU
          path: out/*.zip
